import os
import io
import logging
from typing import Optional
from PIL import Image
from dotenv import load_dotenv

import google.generativeai as genai

# Load environment variables from .env file
load_dotenv()

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Doctor Referral Validation Model Service
# ---------------------------------------------------------------------------
class DoctorValidationService:
    _instance: Optional["DoctorValidationService"] = None

    def __new__(cls) -> "DoctorValidationService":
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._init_client()
        return cls._instance

    def _init_client(self):
        # We still need the key from environment, but internally named generic
        self.api_key = os.getenv("GEMINI_API_KEY")
        if self.api_key:
            try:
                genai.configure(api_key=self.api_key)
                # Try both common names in case of version/region differences
                try:
                    self.model = genai.GenerativeModel('models/gemini-1.5-flash')
                except:
                    self.model = genai.GenerativeModel('models/gemini-pro')
                self.is_configured = True
                logger.info("Validation model configured successfully.")
            except Exception as e:
                logger.error(f"Failed to configure Doctor Validation Model: {e}")
                self.is_configured = False
        else:
            self.is_configured = False

    def generate_validation_report(
        self, image_bytes: bytes, local_score: float, local_label: str
    ) -> dict:
        """
        Generate a detailed validation observation report from the specialized validation model.
        """
        if not self.is_configured:
            logger.warning("Validation model not configured. Skipping report generation.")
            return {
                "validation_report": "Detailed validation insight is currently unavailable."
            }

        try:
            # 1. Load image with PIL
            img = Image.open(io.BytesIO(image_bytes))
            
            # Reduce image size slightly if it's too large to save latency/tokens
            max_size = (1024, 1024)
            img.thumbnail(max_size, Image.Resampling.LANCZOS)

            # 2. Formulate prompt - purely diagnostic observation style
            confidence_pct = local_score * 100
            
            is_liver = "liver" in local_label.lower()
            organ_context = "Liver" if is_liver else "Medical"
            
            prompt = f"""You are a Doctor Referral Validation Model generating a short health observation report from a {organ_context} scan.
Rules:
- Do NOT provide a definitive medical diagnosis.
- If the image is NOT a clear medical scan or if the features are too blurry to identify, state "Image Unclear" under Detected Patterns and set Risk Level to "Inconclusive". 
- Evaluate the visual severity of the indicators shown in the scan. If the initial analysis gives 95% but you see minor indicators, adjust the score in your report.
- Keep the report short and clear. Every bullet point must be a maximum of 1 sentence.
- Avoid long explanations. Use simple bullet points.

Report format:

DOCTOR REFERRAL VALIDATION REPORT

Validation Severity Score: [Provide a precise percentage between 5% and 95% based on visual indicators, e.g. 68%]

Detected Patterns
• Surface Texture: [1 short sentence describing visual texture]
• Coloration/Signal Intensity: [1 short sentence about intensity/color]
• Border Definition: [1 short sentence about edges]
• Visible Lesions/Spots: [1 short sentence]

Identified Symptoms & Disease Signs
• [Identify 1-2 specific visual symptoms or signs related to {organ_context} issues]
• [Mention what these signs might commonly be associated with in clinical literature, without diagnosing the patient]

Risk Level
[Low / Moderate / High]

Suggested Checkup
• [Specialist type 1]

Recommended Tests
• [Specific test name, e.g. Liver Function Test, Ultrasound]

Note
This observation is generated by a validation model and is not a definitive medical diagnosis. Professional medical advice is required.

Generate the report using exactly this format for a {organ_context} scan that is classified as '{local_label}' with {confidence_pct:.1f}% confidence."""

            # 3. Call internal generator with robust model fallback
            logger.info(f"Generating validation report for {local_label} ({confidence_pct:.1f}%)")
            
            # List of model identifiers to try in order of preference
            models_to_try = [
                'gemini-1.5-flash',
                'gemini-1.5-pro',
                'models/gemini-1.5-flash',
                'models/gemini-1.5-pro',
                'gemini-pro',
                'models/gemini-pro'
            ]
            
            last_error = "Unknown"
            response = None
            
            for m_name in models_to_try:
                try:
                    logger.info(f"Trying Doctor Validation Model variant: {m_name}")
                    temp_model = genai.GenerativeModel(m_name)
                    # We need to recreate the generation call for each model attempt
                    response = temp_model.generate_content([prompt, img])
                    if response and response.text:
                        logger.info(f"Successfully generated using {m_name}")
                        break
                except Exception as e:
                    last_error = str(e)
                    logger.warning(f"Model {m_name} failed: {last_error}")
                    continue

            if response and response.text:
                content = response.text.replace("*", "").strip()
                
                # Extract numerical score from the report text (e.g., "Validation Severity Score: 68%")
                refined_score = local_score # Default to CNN score
                import re
                try:
                    # Look for "Score: XX%" where XX is the number
                    match = re.search(r"Validation Severity Score:\s*(\d+)%", content)
                    if match:
                        refined_score = int(match.group(1)) / 100.0
                except:
                    pass

                return {
                    "validation_report": content,
                    "refined_score": refined_score
                }
            else:
                return {
                    "validation_report": f"Error: Failed after trying all models. Last Error: {last_error}",
                    "refined_score": local_score
                }

        except Exception as e:
            logger.error(f"Validation Model Error: {e}")
            return {
                "validation_report": f"Critical Error in Validation Insight: {str(e)}",
                "refined_score": local_score
            }

# Singleton Accessor
_validation_service = DoctorValidationService()

def get_validation_service() -> DoctorValidationService:
    return _validation_service
